# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0002_auto_20170314_0814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='password_based',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password3',
        ),
    ]
