# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0006_file_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_Authority',
            fields=[
                ('id_num', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(default='', max_length=50)),
                ('schoolmaster', models.CharField(default='', max_length=50)),
                ('dean', models.CharField(default='', max_length=50)),
                ('teacher', models.CharField(default='', max_length=50)),
                ('student', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='field',
            field=models.CharField(default='', max_length=50),
        ),
    ]
